# Generated by Django 5.1.3 on 2025-02-02 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0008_alter_customuser_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
