# Generated by Django 5.2 on 2025-04-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
