# Generated by Django 5.2 on 2025-04-27 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_artist_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='downloaded_by',
            field=models.ManyToManyField(blank=True, related_name='downloaded_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
